version: '3'

networks:
  backend:
  billups:
    external: true

services:
  choicesv-golang:
    build: 
      context: ./choice-service
      dockerfile: Dockerfile
    container_name: choicesv_golang
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - backend
      - billups
    labels:
    # This is enableing treafik to proxy this service
      - "traefik.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  traefik:
    image: traefik:v2.3
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.billups.address=:8000"
    restart: always
    ports:
      - "8000:80"
      - "8080:8080" # The Web UI (enabled by --api)
    networks:
      - billups
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock