version: '3'

networks:
  billups:
    external: true

services:
  traefik:
    image: traefik:v2.3
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.billups.address=:8000"
    restart: always
    ports:
      - "8000:8000"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  choicesv:
    build: 
      context: ./choice-service
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 2
    expose:
      - 8081
    labels:
    # This is enableing treafik to proxy this service
      - "traefik.enable=true"
      - "traefik.http.routers.randomchoice.rule=Path(`/choice`)"
      - "traefik.http.routers.choices.rule=Path(`/choices`)"
      - "traefik.http.routers.choicesvhealth.rule=Path(`/choicesv/health`)"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  playsv:
    build: 
      context: ./play-service
      dockerfile: Dockerfile
    environment: 
      - RANDOM_CHOICE_URL=http://traefik:8000/choice
    restart: unless-stopped
    deploy:
      replicas: 1
    expose:
      - 8082
    labels:
    # This is enableing treafik to proxy this service
      - "traefik.enable=true"
      - "traefik.http.routers.playsv.rule=Path(`/play`)"
      - "traefik.http.routers.playsvhealth.rule=Path(`/playsv/health`)"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  